version: '3.8'
services:
  app:
    build: .
    image: goapi
    ports:
      - "13000:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://gopostgresuser:gopostgrespass@db:5432/gopostgresdatabase
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/vendor

  db:
    image: postgres
    environment:
      POSTGRES_DB: "gopostgresdatabase"
      POSTGRES_USER: "gopostgresuser"
      POSTGRES_PASSWORD: "gopostgrespass"
    ports:
      - "13001:5432"

